# Generated by Django 5.0 on 2023-12-25 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=255, verbose_name='Sual')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Cavab')),
                ('display_order', models.PositiveSmallIntegerField(verbose_name='Göstərilmə sırası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Tez-tez verilən sual',
                'verbose_name_plural': 'Tez-tez verilən suallar',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
